### ISSUE TITLE
Time not visible for those of us who use black-background Terminals.

### ISSUE THREAD

**Issue by ghost** [matschaffer/profile#4]

**Comment by matschaffer** [comment]
You should be able to create a ~/.profile.d/environment.conf that has something like this to override the color:

```
show_time() {
  echo "${COLOR_RED}$(date +%H:%M)${COLOR_NONE}"
}
```

Give it a try and let me know.

**Comment by ghost** [comment]
Works. Thanks, Mat. Light Gray seemed to look nice too:

```
echo "${COLOR_LIGHT_GRAY}$(date +%H:%M)${COLOR_NONE}"
```

Nice work on this. Love it.

**Comment by matschaffer** [comment]
Glad you like it! I'll be making some updates soon to hopefully make
these sort of overrides more obvious.

-Mat

On Jun 7, 2011, at 9:58 AM, iq9
reply@reply.github.com
wrote:
