### ISSUE TITLE
Lion install breaks profile

### ISSUE THREAD

**Issue by aarongrando** [matschaffer/profile#7]
See below output from a basic 'cd' command.

> cd ~/
> -bash: PROMPT_COMMAND: line 1: syntax error near unexpected token `&&'
> -bash: PROMPT_COMMAND: line 1:`store_exit_status && update_terminal_cwd;  && { (autojump -a "$(pwd -P)"&)>/dev/null 2>>${HOME}/.autojump_errors;} 2>/dev/null'

Seems related to line 1 of environment.conf. Maybe, hah.

**Comment by matschaffer** [comment]
`update_terminal_cwd; &&` is the issue I think. Should be `update_terminal_cwd &&`. Semicolon and double-ampersands serve the same purpose.

The catch is that I don't have 'update_terminal_cwd' in my directory. Can you `git grep update_terminal_cwd` in .profile.d and see where it's coming from?

If it's not there it might be coming from a .bash_profile or .bashrc, or possibly /etc/profile.

**Comment by matschaffer** [comment]
Thank Ryan for the fix on this one: https://github.com/matschaffer/profile/pull/8
