### ISSUE TITLE
Branch changes indicated when clean

### ISSUE THREAD

**Issue by joecairns** [matschaffer/profile#9]
The change icon,  "変", is displaying constantly even if the branch is clean using git 1.8.0 and 1.8.1 on Mountain Lion.  I'll try rolling back git later today to see if that fixes things.

LOVE this extension btw!

**Comment by matschaffer** [comment]
Thanks @joecairns! Though you may need to look into this issue on your own. I'm on https://github.com/matschaffer/zsh-matschaffer these days.

I suspect that https://github.com/matschaffer/profile/blob/master/environment.conf#L68 needs to get updated for whatever the latest version of git returns. There may even be an exit code you can interpret by now.

**Comment by joecairns** [comment]
Thanks @matschaffer! I'll take a look at implementing a change, but oddly enough, I was thinking of moving over to z-shell as well, now that I know you have an extension of that I may as well go with something more current.

**Comment by matschaffer** [comment]
Cool! Let me know if you hit any issues. I _think_
https://github.com/matschaffer/zsh-autojump may need an update (if you use
autojump)

-Mat

about.me/matschaffer
